# Generated by Django 4.0.1 on 2022-07-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('New Tickets', 'New Tickets'), ('In Progress', 'In Progress'), ('Urgent Tickets', 'Urgent Tickets'), ('Resolved', 'Resolved')], max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
