# Generated by Django 4.0.1 on 2022-07-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
