# Generated by Django 4.0.1 on 2022-07-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ticket_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('Project Manager', 'Project Manager'), ('Submitter', 'Submitter')], max_length=500, null=True)),
            ],
        ),
    ]
