# Generated by Django 4.0.1 on 2022-07-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_project_member_ticket_member_ticket_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.CharField(max_length=2000000, null=True),
        ),
    ]
