# Generated by Django 4.0.1 on 2022-07-10 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_project_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='note',
        ),
    ]
