# Generated by Django 4.0.1 on 2022-07-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_project_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('power', models.CharField(choices=[('Project Manager', 'Project Manager'), ('Team Member', 'Team Member')], max_length=500, null=True)),
                ('project', models.ManyToManyField(to='accounts.Project')),
            ],
        ),
    ]
